### ISSUE TITLE
where is "xf.txt"

### ISSUE THREAD

**Issue by zhangsh950618** [thunlp/TopJudge#1]
Your paper does not mention the use of legal text （xf.txt）as an additional input, nor does it indicate that you use the results of legal predictions as your own input. Why does the content in the code not correspond to the paper?

**Comment by haoxizhong** [comment]
The legal text(xf.txt) contains some information about the law articles, and we have tried to combine these information in our models. However, our implementation with these meta information doesn't work, and **all the models we mentioned in paper have never used this file**. You can think we have some attempts with this file, but it doesn't work with any models, so we don't include it in our paper.  The decoder we use in paper is LSTMDecoder rather than LSTMArticleDecoder.

**Comment by zhangsh950618** [comment]
Thank U

**Comment by haoxizhong** [comment]
(*^▽^*)
